/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_JniLib */

#ifndef _Included_com_example_jnitest_JniLib
#define _Included_com_example_jnitest_JniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_JniLib
 * Method:    getInfo
 * Signature: ()Lcom/example/jnitest/JniInfo;
 */
JNIEXPORT jobject JNICALL Java_com_example_jnitest_JniLib_getInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
